# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = SusyTest0
PACKAGE_PRELOAD  = Tree
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = -lCintex -lReflex -lPyROOT -lXMLParser -lEG
PACKAGE_DEP      = SusyNtuple DGTriggerReweight LeptonTruthTools SusyXSReader SusyMatrixMethod ChargeFlip
PACKAGE_NOOPT    = 0

include $(ROOTCOREDIR)/Makefile-common
